package Panels;


public class ResiboCard extends javax.swing.JPanel {

    public ResiboCard(String name,String quantity,String price,String total) {
        initComponents();
        name_label.setText(name);
        quantity_label.setText(quantity);
        price_label.setText(price);
        total_label.setText(total);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        quantity_label = new javax.swing.JLabel();
        name_label = new javax.swing.JLabel();
        price_label = new javax.swing.JLabel();
        total_label = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        quantity_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        quantity_label.setText("Quantity");
        add(quantity_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 50, 30));

        name_label.setText("Product");
        add(name_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 170, 30));

        price_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        price_label.setText("Price");
        add(price_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 80, 30));

        total_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        total_label.setText("Total");
        add(total_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, 80, 30));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel name_label;
    private javax.swing.JLabel price_label;
    private javax.swing.JLabel quantity_label;
    private javax.swing.JLabel total_label;
    // End of variables declaration//GEN-END:variables
}
